### ISSUE TITLE
This fork should be rebased with bjeavons/zxcvbn-php as there is PHP8 support and other fixes provided there

### ISSUE THREAD

**Issue by jmalinens** [mkopinsky/zxcvbn-php#11]

**Comment by jmalinens** [comment]
or maybe add to README, that people should use bjeavons/zxcvbn-php instead.

As I understand people used your fork because it had more similar password check rules to JS version (thanks for the patches!) but it looks like your patches are accepted now in upstream

**Comment by mkopinsky** [comment]
This fork is now obsolete. I will archive it.
