### ISSUE TITLE
How is this project different from bjeavons/zxcvbn-php ?

### ISSUE THREAD

**Issue by hrvoj3e** [mkopinsky/zxcvbn-php#7]
After reading this thread https://github.com/bjeavons/zxcvbn-php/issues/15 I gathered this:
  - this project is to be more up to date with upstream JS library
  - are the results guaranteed to be the same as with JS lib?

**Comment by mkopinsky** [comment]
Yes, that's correct.

As part of developing this fork we (by which I mean @clamburger) actually compared a whole bunch of the top passwords between the js and php implementations to ensure they both give the same scores.
