### ISSUE TITLE
still inconsistencies ...

### ISSUE THREAD

**Issue by razvanioan** [mkopinsky/zxcvbn-php#9]
After I've first tried the library from bjeavons where the gap between JS & PHP was huge (3 vs 0 as score), I've switched to your fork.

Now the inconsistency is a little bit smaller, but still there is :)

Try `stargate100` (without any user data)

- JS: scores 3
- PHP: scores 2

**Comment by mkopinsky** [comment]
Thanks for the report.

Unfortunately (or fortunately) I can't reproduce this. I get a score of 2
from the js library as well.

Are you using version 4.4.2 of the js library?

>

**Comment by razvanioan** [comment]
Ooops, my bad, it was 4.2.0 ;)

Thx
